### ISSUE TITLE
piFace interrupts

### ISSUE THREAD

**Issue by pedromorgan** [luismesas/goPi#1]
I'm a newbie to piface, and playing with the python API and curious about using golang instead.

I notice.. Interrumpts for PiFace are "EnableInterrupts() Not implemented"
https://github.com/luismesas/goPi/blob/master/piface/piface.go#L88

Is a technical reason that their not implementing, or does the code need writing ?

Am very interested in this area for creating a more "event based, multitasking" application which is not easy with python et al.

**Comment by luismesas** [comment]
You are correct, just need more code writting, I did this library for a personal project with just the needing things. Feel free to contribute with your code as the hard job of integrating to system level has been done.
