### ISSUE TITLE
Incorrect package naming

### ISSUE THREAD

**Issue by pedromorgan** [luismesas/goPi#3]
I notice here..

https://github.com/luismesas/goPi/blob/master/rpi.go

That the package url's are wrong..

should to "goPi" not "go-pi", is this intentional ?/

**Comment by luismesas** [comment]
Just a project rebranding... what do you like most?

**Comment by pedromorgan** [comment]
goPi ;-)

**Comment by pedromorgan** [comment]
This issue you can close as an earlier patch fixed it ;-)
