### ISSUE TITLE
Multiple Boards

### ISSUE THREAD

**Issue by pedromorgan** [luismesas/goPi#4]
I notice that the python API is using a dirrecnt technique for multiple boards..

http://www.piface.org.uk/guides/Using_the_PiFace_Rack/Addressing_multiple_PiFace_Digitals/

Am just pointing this out for curiosity and no other reason

**Comment by luismesas** [comment]
Yes I know, a rpi with the 4 piface expansion boards are rare but they exists. Some refactor will give you this capability as all the core functions supports multiple boards.

I didn't develop it as I don't own this expansion board and I like to own all the things I support.

**Comment by pedromorgan** [comment]
If you want a PiFace board then I can send you one

**Comment by luismesas** [comment]
no thanks, I have a PiFace what I don't have is the expansion for installing 4 PiFace's
